# AxisML Lite repository Makefile. Builds the single axisml-core binary/image.
# Until the shared AxisML modules are published, local development expects the
# axisml checkout beside this repository (../axisml).

REPO_ROOT := $(abspath $(CURDIR))
CORE_DIR := $(CURDIR)/axisml-core
AXISML_REPO ?= ../axisml
IMAGE_TAG ?= dev
IMAGE ?= axisml-core:$(IMAGE_TAG)

# Compose stack: default services are PostgreSQL + axisml-core (published on
# :8090) + axisml-platform (API + UI on :8080). Extra services live behind
# profiles — add them with PROFILES="storage gateway". Requires registry access
# (image build + base-image / workload pulls).
COMPOSE := docker compose -f deploy/docker-compose.yaml
PROFILE_FLAGS := $(foreach p,$(PROFILES),--profile $(p))

.PHONY: help build test vet fmt tidy image doc-gen doc-test client-gen lite-up lite-down lite-delete clean

# axisml-core's OpenAPI spec: the COMPLETE composite HTTP surface. openapi-gen
# folds the three System surfaces — built in-process from each System module's
# pkg/apidoc.Document builder (still owned by the System layer) — into the
# Lite-owned probes + aggregate capability endpoint, since axisml-core serves
# all three modules on one server. No YAML re-read, no ordering dependency on
# the System specs.
LITE_SPEC := docs/apis/axisml-core.yaml
# pkg/core //go:embed-s its own byte-identical copy of the spec (go:embed cannot
# reach across the module boundary into docs/apis), and serves/filters it at
# runtime. doc-gen writes both; doc-test guards them against drift.
LITE_EMBED_SPEC := axisml-core/pkg/core/openapi.gen.yaml

help: ## List targets
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | awk 'BEGIN{FS=":.*?## "}{printf "  %-14s %s\n", $$1, $$2}'

build: ## Build the axisml-core binary
	cd $(CORE_DIR) && go build -o bin/axisml-core ./cmd/axisml-core

test: ## Run unit tests
	cd $(CORE_DIR) && go test ./...

vet: ## go vet (axisml-core + its tools module)
	cd $(CORE_DIR) && go vet ./...
	cd $(CORE_DIR)/tools && go vet ./...

fmt: ## Format
	cd $(CORE_DIR) && gofmt -w cmd internal pkg
	cd $(CORE_DIR) && go run golang.org/x/tools/cmd/goimports@latest -w cmd internal pkg 2>/dev/null || true
	cd $(CORE_DIR)/tools && gofmt -w .
	cd $(CORE_DIR)/tools && go run golang.org/x/tools/cmd/goimports@latest -w . 2>/dev/null || true

tidy: ## Tidy the axisml-core module and its tools module
	cd $(CORE_DIR) && go mod tidy
	cd $(CORE_DIR)/tools && go mod tidy

# openapi-gen lives in the axisml-core/tools module (never published) so its
# pkg/openapigen doc-gen dependency stays OUT of the embeddable axisml-core
# library module — pkg/core only embeds and filters the generated bytes. It
# writes the canonical docs/apis copy and the pkg/core embed copy in one run.
doc-gen: ## Regenerate the axisml-core OpenAPI spec (folds in the System surfaces)
	cd $(CORE_DIR)/tools && go run ./openapi-gen \
	  -o $(REPO_ROOT)/$(LITE_SPEC) \
	  -embed $(REPO_ROOT)/$(LITE_EMBED_SPEC)

doc-test: doc-gen ## Verify the axisml-core spec is in sync with the code
	@cd $(REPO_ROOT) && if ! git diff --quiet -- $(LITE_SPEC) $(LITE_EMBED_SPEC); then \
	  echo "ERROR: axisml-core OpenAPI spec is out of date. Run 'make doc-gen' and commit."; \
	  git --no-pager diff -- $(LITE_SPEC) $(LITE_EMBED_SPEC); exit 1; \
	fi

client-gen: ## Regenerate black-box test clients from the sibling AxisML specs
	@$(MAKE) -C tests client-gen

image: ## Build the axisml-core image (context = repo root)
	docker build --build-context axisml=$(abspath $(AXISML_REPO)) \
	  -f $(CORE_DIR)/Dockerfile -t $(IMAGE) $(REPO_ROOT)

lite-up: ## Bring up the Lite stack (db + axisml-core on :8090 + platform UI on :8080; PROFILES="storage gateway" for more)
	$(COMPOSE) $(PROFILE_FLAGS) up -d --build

lite-down: ## Tear down the Lite stack (CLEAN=1 also removes the data volumes)
	$(COMPOSE) $(PROFILE_FLAGS) down $(if $(CLEAN),--volumes)

# Full purge: the Compose stack + its volumes/networks AND every resource the
# Standalone runtime spawned itself (workload containers + workspace
# volumes labeled io.axisml.managed=true), which `lite-down` does not touch.
lite-delete: ## Purge the Lite stack + all axisml-managed workload containers & volumes
	-@docker rm -f $$(docker ps -aq --filter "label=io.axisml.managed=true") 2>/dev/null || true
	$(COMPOSE) down --volumes --remove-orphans
	-@docker volume rm $$(docker volume ls -q --filter "label=io.axisml.managed=true") 2>/dev/null || true

# The black-box e2e suite is Python + pytest under tests/ (not a make target).
# Bring the Lite stack up first (`make lite-up`), then from the repo root:
#   cd tests && uv sync && uv run test-setup --mode lite
#   uv run pytest --mode lite

clean: ## Remove build artifacts
	rm -rf bin
