package core

// OpenAPISpec is axisml-core's single seam for its own HTTP contract: it returns
// the OpenAPI 3.0.3 description of the surface App.Handler serves — the three
// System modules (Cluster Manager + Compute Service + Artifact Hub) folded onto
// one server plus the Lite-owned probes and aggregate capability endpoint —
// optionally scoped to a path allowlist.
//
// It is a package-level function, not a method on App, on purpose: the contract
// is static, so emitting it needs no database, Docker daemon or running App. An
// embedder generates its published spec in a plain doc-gen step with only a
// pkg/core import; App additionally serves the same bytes at runtime (see
// openapiHandler in app.go).
//
// The composite document is generated at build time by axisml-core/tools/openapi-gen
// (which owns the reflection-based fold of the three System surfaces) and embedded
// here as openapi.gen.yaml. Keeping the generator in the never-published tools
// module means the pkg/openapigen doc-gen dependency never enters the library an
// external project embeds — pkg/core only parses and filters the bytes it already
// carries. The scope+prune, header-injection and info-reframing logic below is the
// only spec logic that runs at the embedder's runtime, and it works on the decoded
// document so it needs no OpenAPI model type.

import (
	_ "embed"
	"encoding/json"
	"fmt"
	"strings"

	"sigs.k8s.io/yaml"
)

// openapi.gen.yaml is the byte-identical in-package copy of
// axisml-lite/docs/apis/axisml-core.yaml, regenerated by `make -C axisml-lite
// doc-gen`. go:embed cannot reach across the module boundary into docs/apis, so
// the library keeps its own copy; doc-test guards the two against drift.
//
//go:embed openapi.gen.yaml
var embeddedSpec []byte

// defaultSpecVersion is the info.version baked into the embedded document; a
// caller that does not override it via WithVersion/WithInfo gets the verbatim
// bytes back.
const defaultSpecVersion = "0.0.0-dev"

const schemaRefPrefix = "#/components/schemas/"

// httpVerbs are the OpenAPI operation keys within a path item.
var httpVerbs = []string{"get", "post", "put", "patch", "delete"}

// SpecFormat selects OpenAPISpec's serialization.
type SpecFormat int

const (
	// SpecYAML renders the document as YAML (the zero value).
	SpecYAML SpecFormat = iota
	// SpecJSON renders the document as pretty-printed JSON.
	SpecJSON
)

// SpecOption configures OpenAPISpec.
type SpecOption func(*specOptions)

type specInfo struct {
	title, version, description string
}

type headerParam struct {
	name, description string
	required          bool
}

type specOptions struct {
	version      string
	info         *specInfo
	pathPrefixes []string
	header       *headerParam
}

// WithVersion sets info.version. WithInfo, if also given with a non-empty
// version, takes precedence.
func WithVersion(version string) SpecOption {
	return func(o *specOptions) { o.version = version }
}

// WithPathPrefixes scopes the returned document to operations whose path equals
// or is nested under one of the given prefixes; components.schemas is pruned to
// the transitive $ref closure of the kept operations (no dangling refs, no
// leakage of unexposed resources) and tags with no surviving operation are
// dropped. Nesting is matched on a path-segment boundary, so the prefix
// "/api/v1/resourcepools" keeps "/api/v1/resourcepools/{pool}" but not an
// unrelated "/api/v1/resourcepools-archive". Passing no prefixes keeps the full
// surface.
func WithPathPrefixes(prefixes ...string) SpecOption {
	return func(o *specOptions) { o.pathPrefixes = append(o.pathPrefixes, prefixes...) }
}

// WithGlobalHeaderParam adds a header parameter to every kept operation — an
// embedder documents an identity header its gateway requires (e.g. X-Axisml-User)
// without hand-editing the emitted document.
func WithGlobalHeaderParam(name, description string, required bool) SpecOption {
	return func(o *specOptions) {
		o.header = &headerParam{name: name, description: description, required: required}
	}
}

// WithInfo overrides the document's info block for an embedder's own branding.
// Empty fields are left at the axisml-core default.
func WithInfo(title, version, description string) SpecOption {
	return func(o *specOptions) {
		o.info = &specInfo{title: title, version: version, description: description}
	}
}

// OpenAPISpec renders the (optionally scoped) composite spec as bytes. With no
// options and SpecYAML it returns the embedded document verbatim; otherwise it
// decodes, transforms and re-marshals it. The output is deterministic (map keys
// are sorted), so callers can commit it and diff-check it in CI.
func OpenAPISpec(format SpecFormat, opts ...SpecOption) ([]byte, error) {
	o := specOptions{version: defaultSpecVersion}
	for _, opt := range opts {
		opt(&o)
	}

	// The embedded YAML is already the full document; only decode when an option
	// (or a non-YAML format) actually changes it.
	if format == SpecYAML && len(o.pathPrefixes) == 0 && o.header == nil && o.info == nil && o.version == defaultSpecVersion {
		out := make([]byte, len(embeddedSpec))
		copy(out, embeddedSpec)
		return out, nil
	}

	var doc map[string]any
	if err := yaml.Unmarshal(embeddedSpec, &doc); err != nil {
		return nil, fmt.Errorf("openapi: parse embedded spec: %w", err)
	}

	if len(o.pathPrefixes) > 0 {
		scopeToPrefixes(doc, o.pathPrefixes)
	}
	if o.header != nil {
		addHeaderParam(doc, *o.header)
	}
	applyInfo(doc, o)

	switch format {
	case SpecYAML:
		return yaml.Marshal(doc)
	case SpecJSON:
		return json.MarshalIndent(doc, "", "  ")
	default:
		return nil, fmt.Errorf("openapi: unknown spec format %d", format)
	}
}

// scopeToPrefixes drops every path outside the allowlist, prunes
// components.schemas to the transitive $ref closure of the surviving operations
// and removes now-empty tags.
func scopeToPrefixes(doc map[string]any, prefixes []string) {
	paths, _ := doc["paths"].(map[string]any)
	kept := map[string]any{}
	for p, item := range paths {
		if matchesAnyPrefix(p, prefixes) {
			kept[p] = item
		}
	}
	doc["paths"] = kept

	if schemas, ok := nestedMap(doc, "components", "schemas"); ok {
		reachable := reachableSchemaNames(kept, schemas)
		for name := range schemas {
			if !reachable[name] {
				delete(schemas, name)
			}
		}
	}

	pruneTags(doc, kept)
}

func matchesAnyPrefix(path string, prefixes []string) bool {
	for _, pre := range prefixes {
		if path == pre || strings.HasPrefix(path, pre+"/") {
			return true
		}
	}
	return false
}

// reachableSchemaNames computes the set of component schema names reachable from
// the kept paths: it seeds from every $ref anywhere in those path items and
// chases refs transitively through the component definitions.
func reachableSchemaNames(keptPaths, schemas map[string]any) map[string]bool {
	seed := map[string]bool{}
	for _, item := range keptPaths {
		collectRefs(item, seed)
	}

	reachable := map[string]bool{}
	queue := make([]string, 0, len(seed))
	for name := range seed {
		queue = append(queue, name)
	}
	for len(queue) > 0 {
		name := queue[len(queue)-1]
		queue = queue[:len(queue)-1]
		if reachable[name] {
			continue
		}
		reachable[name] = true
		if s, ok := schemas[name]; ok {
			next := map[string]bool{}
			collectRefs(s, next)
			for n := range next {
				if !reachable[n] {
					queue = append(queue, n)
				}
			}
		}
	}
	return reachable
}

// collectRefs records every #/components/schemas/<name> reference found anywhere
// in the decoded subtree.
func collectRefs(node any, into map[string]bool) {
	switch n := node.(type) {
	case map[string]any:
		if ref, ok := n["$ref"].(string); ok && strings.HasPrefix(ref, schemaRefPrefix) {
			into[strings.TrimPrefix(ref, schemaRefPrefix)] = true
		}
		for _, v := range n {
			collectRefs(v, into)
		}
	case []any:
		for _, v := range n {
			collectRefs(v, into)
		}
	}
}

// pruneTags drops tag definitions no surviving operation references.
func pruneTags(doc, keptPaths map[string]any) {
	tagsList, ok := doc["tags"].([]any)
	if !ok {
		return
	}
	used := map[string]bool{}
	for _, item := range keptPaths {
		for _, op := range operationMaps(item) {
			if tags, ok := op["tags"].([]any); ok {
				for _, t := range tags {
					if s, ok := t.(string); ok {
						used[s] = true
					}
				}
			}
		}
	}
	kept := make([]any, 0, len(tagsList))
	for _, t := range tagsList {
		if tm, ok := t.(map[string]any); ok {
			if name, ok := tm["name"].(string); ok && used[name] {
				kept = append(kept, t)
			}
		}
	}
	doc["tags"] = kept
}

// addHeaderParam appends a header parameter to every operation in the document.
func addHeaderParam(doc map[string]any, h headerParam) {
	paths, _ := doc["paths"].(map[string]any)
	for _, item := range paths {
		for _, op := range operationMaps(item) {
			param := map[string]any{
				"name":        h.name,
				"in":          "header",
				"description": h.description,
				"schema":      map[string]any{"type": "string"},
			}
			if h.required {
				param["required"] = true
			}
			params, _ := op["parameters"].([]any)
			op["parameters"] = append(params, param)
		}
	}
}

// applyInfo overrides the info block from WithInfo, or just info.version from
// WithVersion (WithInfo wins).
func applyInfo(doc map[string]any, o specOptions) {
	info, ok := doc["info"].(map[string]any)
	if !ok {
		info = map[string]any{}
		doc["info"] = info
	}
	if o.info != nil {
		if o.info.title != "" {
			info["title"] = o.info.title
		}
		if o.info.version != "" {
			info["version"] = o.info.version
		}
		if o.info.description != "" {
			info["description"] = o.info.description
		}
		return
	}
	if o.version != defaultSpecVersion {
		info["version"] = o.version
	}
}

// operationMaps returns the operation objects (by HTTP verb) of a path item.
func operationMaps(item any) []map[string]any {
	m, ok := item.(map[string]any)
	if !ok {
		return nil
	}
	var ops []map[string]any
	for _, verb := range httpVerbs {
		if op, ok := m[verb].(map[string]any); ok {
			ops = append(ops, op)
		}
	}
	return ops
}

// nestedMap descends a chain of map keys, returning the terminal map.
func nestedMap(m map[string]any, keys ...string) (map[string]any, bool) {
	cur := m
	for _, k := range keys {
		next, ok := cur[k].(map[string]any)
		if !ok {
			return nil, false
		}
		cur = next
	}
	return cur, true
}
